config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  root to: "offers#index"

  resources :offers
  
  

end

app/models/offer.rb
class Offer < ActiveRecord::Base
 validates :code, uniqueness: true, presence: true,
 	format: { with: /\[with0-9A-Z]{8}$\z/,
 	message: "Offer code must be 8 characters using capital letters and numbers"}
 #validates :deadline, 
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  before_action :authenticate_user!
  def index
  	@offers = Offer.all
  end

  def show
    @offer = Offer.find(params[:id])
  end

  def new
    @offer = Offer.new
  end

  def create
    @offer = Offer.new(offer_params)
    if @offer.save
      redirect_to(:action => 'index')
    else
      render('new')
    end
  end

  def edit
    @offer = Offer.find(params[:id])
  end

  def update
    @offer = Offer.find(params[:id])
    if @offer.update_attributes(offer_params)
      redirect_to(:action => 'index', :id => @offer.id)
    else
      render('edit')
    end
  end

  def delete
    @offer = Offer.find(params[:id])
  end

  def destroy
    Offer.find(params[:id]).destroy
    redirect_to(:action => 'index')
  end

  private
#strong params! :code... for Rails 4!
  def offer_params
   	params.require(:offer).permit(:code, :title, :description, :house_rules, :deadline)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= I18n.t(:"activerecord.errors.header", :default => "Invalid Fields")
    options[:message] ||= I18n.t(:"activerecord.errors.message", :default => "Correct the following errors and try again.")
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/views/layouts/_flash_messages.html.erb
    <% flash.each do |name, msg| %>
      <% if msg.is_a?(String) %>
      <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      </div>
      <% end %>
    <% end %>

app/views/layouts/_main_menu.html.erb
    <header>
      <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <%= link_to 'Home', root_path, class: 'navbar-brand' %>
          </div>
          <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
              <% if user_signed_in? %>
              <li><%= link_to 'Offers', offers_path %></li>
              <% end %>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <% if user_signed_in? %>
              <li><%= link_to 'Edit account', edit_user_registration_path %></li>
              <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
              <% else %>
              <li><%= link_to 'Sign in', new_user_session_path %></li>
              <li><%= link_to 'Sign up', new_user_registration_path %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
  </head>
  <body>
    <%= render 'layouts/main_menu' %>
    <div id="main">
      <!-- To comunicate !CSS to the html= instead "id" we rename it as a "class" -->
      <%= render 'layouts/flash_messages' %>
      <%= content_tag :h1, yield(:title) if show_title? %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/offers/_form.html.erb
<%= bootstrap_form_for(@offer) do |f| %>
  <%= f.text_field :code %>
  <%= f.text_field :title, class: 'title_box' %>
  <%= f.text_area :description, { class: 'text_area', rows: 30 } %>
  <%= f.text_area :house_rules, { class: 'text_area', rows: 20 } %>
  <%= f.text_field :deadline, { class: 'datepicker', "data-provide" => "datepicker", "data-date-format" => "yyyy-mm-dd" } %>
  <%= f.submit %>
<% end %>

app/views/offers/edit.html.erb
<h1>Edit Offer</h1>

<%= render 'form' %>

<%= link_to icon('chevron-left', 'Back'), offers_path, class: "btn btn-default" %>

app/views/offers/index.html.erb
<h1>All Offers</h1>

<h2>A full list of all offers in the database</h2>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Offer Code</th>
      <th>Offer Title</th>
      <th>Deadline</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
  <% @offers.each do |offer| %>
    <tr>
      <th scope="row"><%= offer.code %></th>
      <td><%= offer.title %></td>
      <td><%= offer.deadline.try(:strftime, "%Y/%m/%d") %></td>
      <td><%= link_to icon('edit', 'Edit'), edit_offer_path(offer.id), class: "btn btn-primary" %></td>
      <td><%= link_to icon('newspaper-o', 'Show'), offer_path(offer.id), class: "btn btn-info" %></td>
      <td><%= link_to icon('close', 'Delete', class: 'text-danger'), offer_path(offer.id), method: :delete, data: {confirm: "Are you sure you want to delete this offer?"}, class: "btn btn-danger" %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<%= link_to  link_to icon('plus', 'Add New Offer'), new_offer_path, class: "btn btn-default" %>

app/views/offers/new.html.erb
<h1>Create New Offer</h1>

<%= render 'form' %>

<%= link_to icon('chevron-left', 'Back'), offers_path, class: "btn btn-default" %>

app/views/offers/show.html.erb
<h1>Offer Details</h1>

<p>
	<strong>Offer Code:</strong><br>
	<%= @offer.code %>
</p>
<br>
<p>
	<strong>Offer Title:</strong><br>
	<%= @offer.title %>
</p>
<br>
<p>
	<strong>Description:</strong><br>
	<%= simple_format(strip_tags(@offer.description)) %>
</p>
<br>
<p>
	<strong>House Rules:</strong><br>
	<%= simple_format(strip_tags(@offer.house_rules)) %>
</p>
<br>
<p>
	<strong>Deadline:</strong><br>
	<%= @offer.deadline.try(:strftime, "%Y/%m/%d") %>
</p>

<%= link_to icon('close', 'Delete', class: 'text-danger'), offer_path(@offer), method: :delete, data: {confirm: "Are you sure you want to delete this offer?"}, class: "btn btn-danger" %>
<%= link_to icon('edit', 'Edit'), edit_offer_path(@offer), class: "btn btn-primary" %>
<%= link_to icon('chevron-left', 'Back'), offers_path, class: "btn btn-default" %>